#!/usr/bin/env bash

set -euo pipefail

ASDF_DIR=${ASDF_DIR:-$HOME/.asdf}

ASDF_GLOBAL_BIN_DIR=${ASDF_GLOBAL_BIN_DIR:-$HOME/.bin}
mkdir -p "$ASDF_GLOBAL_BIN_DIR"

# clean all existing asdf links
# TODO: clear only broken links?
for f in "$ASDF_GLOBAL_BIN_DIR"/*; do
    if [[ $(readlink -f "$f") == ${ASDF_DIR}* ]]; then
        echo "Removing $f"
        rm "$f"
    fi
done

while read -r line; do
    IFS=' ' read -ra fields <<<"$line"
    name=${fields[0]}

    if install_path=$(asdf where "$name"); then
        install_bin="${install_path}/bin"

        for f in "$install_bin"/*; do
            echo "Linking $f -> $ASDF_GLOBAL_BIN_DIR/$(basename "$f")"
            ln -s "$f" "${ASDF_GLOBAL_BIN_DIR}/"
        done
    fi

done <<<"$(grep -v '\s*#\|^$' "$HOME/.tool-versions")"
# ^ strip lines with leading comments or blank lines
